### ISSUE TITLE
Yanıt kutusunun text taşırması

### ISSUE THREAD

**Issue by INorthDev** [metwcc/ptb.metw.cc#3]
Linkler gibi uzun yazılar bazen text box'a sığmayabiliyor.

![Screenshot_20220815-220220_Brave](https://user-images.githubusercontent.com/80062997/184700089-5f368470-8b4c-4456-9559-c2dc9f7bf7d9.jpg)

![Screenshot_20220815-220225_Brave](https://user-images.githubusercontent.com/80062997/184700099-a499246b-07be-41fa-b1ae-fc4057b40ade.jpg)

**Comment by metwse** [comment]
Ooo, evet, düzeltilmeli 👍

**Comment by metwse** [comment]
düzeltildi
